### ISSUE TITLE
US 2: Login system for every user.

### ISSUE THREAD

**Issue by KapJ1coH** [airicodes/Framenotwork_SOEN341_Project_F24#2]
**As a user, I want a login system that allows secure sign-in and sign-up so that I can access the application according to my role as either a Student or Instructor.**

### **Main Points:**
- Enable secure login and account creation.
- Differentiate user roles between Student and Instructor.
- Store user information securely in the database.
- Provide unique dashboards for logged-in Students and Instructors.

### **Tasks:**
- [x] #90
- [x] #91
- [x] #92
- [x] #93
- [x] #94
- [x] #95
- [x] #96
- [x] #97
- [x] #98

### **Acceptance Tests:**
- [x] #99
- [x] #100

**Comment by KapJ1coH** [comment]
- [ ] Task9 - Create backend for the login system

**Comment by KapJ1coH** [comment]
Time taken for the project: 10.5h

**Comment by bulabd** [comment]
Time taken to create database: 4h

**Comment by 20Mathieu03** [comment]
Time to complete US#2: 10h

**Comment by jdplao** [comment]
Time taken to design web pages: 2h30
