### ISSUE TITLE
US 4: Move students between groups

### ISSUE THREAD

**Issue by KapJ1coH** [airicodes/Framenotwork_SOEN341_Project_F24#5]
**As an instructor, I need the ability to assign or move students to specific groups so that I can effectively manage team compositions and ensure balanced teams in my course.**

### **Main Points:**
- Move students between groups.
- Validate assignments to prevent errors.
- Update database and UI upon successful moves.

### **Tasks:**
- [x] #38
- [x] #39 

### **Acceptance Tests:**
- [x] #76
- [x] #77

**Comment by airicodes** [comment]
The ability to view and select students has been completed.

**Comment by KapJ1coH** [comment]
> The ability to view and select students has been completed.

- If it's done and merged, can you mark this issue as done and same with the sub-tasks? 
- Also add the time you've spent into the log
- Put the amount you've spent into the excel
