### ISSUE TITLE
US 5: User Authentification & Team management: Ability to see the teams and students

### ISSUE THREAD

**Issue by KapJ1coH** [airicodes/Framenotwork_SOEN341_Project_F24#6]
**As an instructor or student, I want to view the teams and their members so that I can understand team compositions and know who is in each group.**

### **Main Points:**
- View teams and members.
- Maintain user sessions.
- Display relevant courses and enrolled students.

### **Tasks:**
- [x] #40 
- [x] #64
- [x] #65
- [x] #66

### **Acceptance Tests:**
- [x] #86
- [x] #87

**Comment by airicodes** [comment]
Base example has been done on the instructor side.

**Comment by KapJ1coH** [comment]
> Base example has been done on the instructor side.

Same thing here, close the issue once it's done
